FROM openjdk:8-jre-alpine
ENV APP_FILE eureka-server.jar
ENV APP_HOME /usr/apps
EXPOSE 8761
COPY build/libs/$APP_FILE $APP_HOME/
WORKDIR $APP_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $APP_FILE"]