apiVersion: v1
kind: Namespace
metadata:
  name: eureka-server-namespace
  labels:
    name: eureka-server-namespace-label
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  namespace: eureka-server-namespace
spec:
  selector:
    app: eureka-server-pod-label
  ports:
    - protocol: TCP
      nodePort: 31234
      port: 8080
      targetPort: 8761
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: eureka-server-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server-pod-label
  template:
    metadata:
      name: eureka-server-pod
      labels:
        app: eureka-server-pod-label
    spec:
      containers:
        - name: eureka-server-container
          image: praveshgupta1993/eureka-server:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8761