apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    app: eureka-server-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server-deployment-label
  template:
    metadata:
      labels:
        app: eureka-server-deployment-label
    spec:
      containers:
      - name: eureka-server-pod
        image: praveshgupta1993/eureka-server:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  labels:
    app: eureka-server-service-label
spec:
  ports:
  - name: http
  	port: 80
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-server-pod